use_frameworks!

platform :ios, '10.0'

target 'TGASDK-Swift' do
  pod 'TGASDK', :path => '../'
  
  pod 'CocoaDebug', '~> 1.7.2'
  pod 'AppLovinMediationAdColonyAdapter', '~> 4.9.0.0.2'
  #pod 'AppLovinMediationUnityAdsAdapter'
  pod 'AppLovinMediationVungleAdapter', '~> 6.12.0.2'
end

target 'TGASDK-OC' do
  pod 'TGASDK', :path => '../'
  pod 'AppLovinMediationAdColonyAdapter', '~> 4.9.0.0.2'
  #pod 'AppLovinMediationUnityAdsAdapter'
  pod 'AppLovinMediationVungleAdapter', '~> 6.12.0.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
